# This config is used to configure layout only for "GitHub Pages". 
# To configure all layouts for mkdocs themes, use mkdocs.yml.

title: "PH8124: Scientific computing in high-energy physics"
#description: Project documentation
theme: jekyll-theme-primer # this gives the same default layout, if _config.yml is not used
show_downloads: false
