site_name: "PH8124: Scientific computing in high-energy physics"

theme:
  name: mkdocs
#  name: material
#  name: readthedocs

# common navigation settings for all themes:
#nav:
#  - Home: index.md

# common extra CSS for all themes:
extra_css:
  - stylesheets/extra.css

# specific settings for individually themes:
hooks:
  - docs/hooks/conditional_nav.py # navigation settings but conditional and specific for each theme
  - docs/hooks/conditional_css.py # extra CSS but conditional and specific for each theme


#  analytics:
#    gtag: G-ABC123
#  shortcuts:
#    help: 191    # ?
#    next: 78     # n
#    previous: 80 # p
#    search: 83   # s

# support for math:
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # online math
#  - javascripts/tex-mml-chtml.js # offline math


# Optional but useful
# plugins:
#  - search

